### ISSUE TITLE
Can't find donation link.

### ISSUE THREAD

**Issue by jeff-zone** [pngan/winlayout#11]
Thank you for making this.  I have been looking for a good fix for windows that get messed up when windows 10 goes into sleep or hibernate and your program fixes this problem.  It's been saving me a lot of time.  Please put a donation link somewhere.

**Comment by pngan** [comment]
I'm extremely flattered .
Knowing that someone has benefited is enough reward for me.

**Comment by pngan** [comment]
@jeff-zone  FYI winlayout has been updated to accommodate multiple save configurations.
