### ISSUE TITLE
Windows moved to the right screen, but positions within the screen are not restored correctly

### ISSUE THREAD

**Issue by DSA101** [pngan/winlayout#3]
Repro:
1. Laptop in a dock with 2 monitors attached. A number of windows are opened and moved on each screen using start+left(right) arrow to take half of the screen.
2. Run winlayout save
3. Undock laptop.
4. Re-docok laptop.
5. All windows are on the main screen.
6. Run winlayout restore
7. Bug: Windows moved to the correct screens (except Sticky Notes that stayed on the main screen), but they appeared in some default random position rather than pinned to left or right as before "save". Sticky Notes did not move to the right screen.

**Comment by pngan** [comment]
Try again with a later version, that implements the jiggle work around.
