### ISSUE TITLE
Running winlayout save or restore throws an error

### ISSUE THREAD

**Issue by T931D** [pngan/winlayout#4]
Running the command throws the following error:
`The applicaation to execute does not exist: 'C:\Users\User\Appdata\Local\Temp\.net\winLayout \eoadb1ua.z5u\winLayout.dll'`
Any idea what causes this and how to fix it?

**Comment by alexisohayon** [comment]
I have the same issue 🤚

**Comment by smash388** [comment]
I was trying to fix #6 so I deleted all the files in `C:\Users\User\Appdata\Local\Temp\.net\winLayout\eoadb1ua.z5u\` and then I received the error `The application to execute does not exist: C:\Users\User\Appdata\Local\Temp\.net\winLayout\eoadb1ua.z5u\winLayout.dll`. Deleting the eoadb1ua.z5u folder resolved the error.

**Comment by pngan** [comment]
Thanks for the workaround @smash388
