### ISSUE TITLE
not working after win10 x64 updates. Please recompile with new .NET

### ISSUE THREAD

**Issue by lswist** [pngan/winlayout#6]

**Comment by tony-in-nz** [comment]
Error:
  An assembly specified in the application dependencies manifest (winLayout.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.0.0-preview8-28405-07'
    path: 'Microsoft.CSharp.dll'

**Comment by smash388** [comment]
I was able to resolve this issue by deleting the folder `C:\Users\User\Appdata\Local\Temp\.net\winLayout\eoadb1ua.z5u\`.

**Comment by pngan** [comment]
winlayout has now been recompiled with .net 5.
