### ISSUE TITLE
winLayout.exe is not available for download

### ISSUE THREAD

**Issue by creeve4** [pngan/winlayout#9]
I would like to use winLayout from the command line per your instructions, but winLaout.exe is not available for download.

```Alternatively, Install and Use Command Line
With the laptop running on the docking station, and application windows in their desired locations, download winLayout.exe run the command:

winlayout save

Then the next time the laptop is plugged into the docking station, the window locations of the running applications can be restored by the command:

winlayout restore

For convenience, make a windows short cut to the file winlayout.exe (with the desired parameter) and pin to the task bar for easy access.```

**Comment by creeve4** [comment]
I was able to build winLayout.exe, but I get the following error when executing `winLayout save`

```Error:
  An assembly specified in the application dependencies manifest (winLayout.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '5.0.17'
    path: 'clrcompression.dll'```

**Comment by creeve4** [comment]
Apparently all files in the Publish folder are needed. It is now working, although there is a long 5-10 second delay when executing save and restore from the command line. Any idea why there is this delay?

**Comment by pngan** [comment]
@creeve4  I've added a build.bat that can build the executables with a single command line. The final executable is copied to the top level directory. I've run the executable and it runs quickly on my machine.

**Comment by creeve4** [comment]
Thank you!
